name: 📄✨ Release CV

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - .github/workflows/latex.yaml
      - '**.tex'
      - '**.toml'

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🚀 Set Up Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          tectonic-version: 0.15.0
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧹 Clear Tectonic Cache
        run: rm -rf ~/.cache/Tectonic

      - name: 🏗️ Build Resume in LaTeX
        run: tectonic -X build --keep-logs

      - name: ✨ Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: build/SinaAboutalebi/SinaAboutalebi.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}